### ISSUE TITLE
UI idea: after tapping/clicking on a piece, show the possible places that piece can move to

### ISSUE THREAD

**Issue by simondorfman** [skotz/chase-ai#10]
the chess.com app has this feature, but you have to turn it on in preferences.

Screenshot below.
I tapped the knight and it shows the possible squares the knight can move with gray circles over those squares:
![img_9745](https://cloud.githubusercontent.com/assets/106923/21183837/5cf8da4c-c1cf-11e6-9516-74b0b325ecac.PNG)

**Comment by skotz** [comment]
Implemented!
