### ISSUE TITLE
Idea for machine learning: feed the history of games played at superdupergames.org

### ISSUE THREAD

**Issue by simondorfman** [skotz/chase-ai#12]
Here's where you find the chase game history:

1. go here: http://superdupergames.org/main.html?page=listoldgames
2. choose "Chase" from the "Select Games to view" list.
3. click "View Archives"

It doesn't have the full archive of games, but I can contact Aaron and ask for a database dump of all games if you want to explore this idea.

**Comment by skotz** [comment]
It's a good idea, but we'd have to filter to just the games played by experts. I'm worried that at best we'd train the engine to learn bad habits. As it is now, the brute force method of analyzing 8 million+ lines per second seems like the way to go.

**Comment by simondorfman** [comment]
yeah, good point. maybe just limit it to ladder game challenges involving the player at the top of the ladder. but maybe just brute force is the way to go. there haven't been that many games played. i bet an AI could teach us a lot of strategies and tactics that haven't been discovered by humans yet.

can you point me to the code, or maybe better yet, give me a layman's explanation for how you're prioritizing the brute force method?

for example, when you've got 5 dice in hand, the highest priority is to not get captured so you don't lose the game. whereas early in the game, it's okay to exchange several pieces as long as you come out ahead in some way (maybe more chamber setups).

**Comment by skotz** [comment]
The specific code that searches the tree of possible moves and evaluates positions at the end of each of those lines is here:

https://github.com/skotz/chase-ai/blob/master/Chase.Engine/Search.cs

I'm using the minimax algorithm with alpha-beta pruning. Basically I'm recursively finding every move, every counter move to each of those moves, and so on several layers deep until it becomes computationally infeasible to search any further. At that point we have to assign a value to that position so it can bubble back up the tree and let us find good moves. 

Right now for the evaluation I'm just figuring in material counts (blue piece count minus red piece count, so larger values are better for blue and negative values are better for red). I have plans to figure in mobility (number of available moves to choose from), but my first attempt dropped the search speed by nearly 99%, so I took it out for now. With this evaluation alone the computer is finding ways to capture enemy pieces, avoid captures itself, and split. I'm also seeing a pattern where one computer player surrounds the chamber with 1s and 2s so the other player can't split but can always recapture. Interesting.

**Comment by skotz** [comment]
By the way, I tried playing a quick game against the engine just now and it slaughtered me. 

A9-A1 A8-A9 A7-A8 A6-A7 A5-A6 A4-A5 A3-A4 A2-A3 A1-A2 I6-E8 CH-D5 CH-E6 A7-CH I4-E6 A2+=2 A5-E3 E8-E3 A1+=4 A4-D6 I8-G7 A9-A8+=1 I1-H2 A8-A7 A9-A8 E3-A1 A8+=5 D5-D6+=1 A1-E8 D6-B4 E6-A4 D5-C4 CH-D5 CH-E6 A7-CH G7-E6 C4+=2 D5-D7 I5-D3 A3-A2+=1 D3-D7 A3+=2 A3-A2+=2 D7-C4 A3+=3 A6-F4 I2-G3 A8-G2 I7-F6 F4-G6 I3-F5 A2-G8 I9-H1 G6-F4 H2-G2

**Comment by skotz** [comment]
Closing since I don't see much promising research related to neural network driven chess (or chase) engines.
