### ISSUE TITLE
UI Idea: section to write notes to yourself

### ISSUE THREAD

**Issue by simondorfman** [skotz/chase-ai#13]
superdupergames.org has this feature. it's useful for asynchronous play where you want to write notes to yourself so you remember you plan when you look at your next turn. You can store notes like: if he does x, do y, then probably z, etc.

**Comment by skotz** [comment]
I can see this being useful for correspondence games with multi-day time controls.

**Comment by skotz** [comment]
Since this is a stand-alone game I'm not sure how this would fit in. I'm going to close it for now. Maybe if I port this to JavaScript and implement some way to play correspondence online, I'll re-consider this.
