### ISSUE TITLE
UI idea: show pieces that are in danger of capture, a.k.a. Atari in Go

### ISSUE THREAD

**Issue by simondorfman** [skotz/chase-ai#14]
Sometimes it's hard to see when your pieces are in danger, especially wraparound bounce-bump-captures. Wraparound moves in general are hard to see, especially for new players. Somehow show when a piece is in danger via the UI.

This courtesy is similar to the convention of saying Atari when playing Go to let the opponent know they are in danger of capture: https://en.wikipedia.org/wiki/List_of_Go_terms#Atari

**Comment by skotz** [comment]
This would be very helpful. Probably needs discussion of whether it would be fair if playing another human.

**Comment by skotz** [comment]
Implemented! It even works when the capture is through a bump or split.

![screenshot-2016-12-16-c](https://cloud.githubusercontent.com/assets/11474654/21272958/ee807d9a-c386-11e6-971b-289bd0202ab1.png)

![screenshot-2016-12-16-b](https://cloud.githubusercontent.com/assets/11474654/21272960/f2d160bc-c386-11e6-87d1-943484764766.png)
