### ISSUE TITLE
Read up on the official rules of the game

### ISSUE THREAD

**Issue by skotz** [skotz/chase-ai#22]
See if there's special rules for things like landing on the chamber when you already have 10 pieces or if you repeat the same position 3 time it's a draw (if that's a rule).

**Comment by simondorfman** [comment]
1. If you have 10 pieces on the board & you move a piece into the chamber, the piece doesn't split into 2 pieces, instead it just comes out of the chamber to the left. In other words, when an odd numbered piece (E.g. a 5) chambers, the larger of the split dice comes out on the left (e.g. a 3 comes out on the left). That spot where the 3 comes out of the chamber is the same spot where any piece would come out of the chamber when you have 10 pieces on the board.
2. I don't know of any rule in chase where it's not allowed to repeat the same position 3 times in a row, but that's probably a deficiency in the rules that needs to be addressed. I'd suggest adopting the way Go solves this problem: making a move illegal if it returns the game state to the same place it was on a previous turn, called the ko rule. More info on that here: https://en.m.wikipedia.org/wiki/Rules_of_go#Ko

**Comment by skotz** [comment]
1. Great. This is how I currently have it implemented.
2. I like the idea of making the move illegal. In chess you have 3-fold repetition and the 50 move rule, both of which are defined as draws.

**Comment by skotz** [comment]
I've implemented the second idea loosely. The engine will avoid position repetition as if it was illegal, but it will allow it if you repeat a position playing against it.

Since I feel the rules are pretty much correct, I'm going to close this issue. I'll create a new issue if the engine starts making invalid moves or a new rule is discovered.
